using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KSS.Control.Controls
{
    /// <summary>
    /// Represents a control that responds to signals generated by a <see cref="ControllerOutput{T}"/>.
    /// </summary>
    public sealed class ControlleeInput<T> : Control
    {
        internal Action<T> onInvoke;

        public ControllerOutput<T> Output { get; internal set; }

        /// <param name="signalResponse">The action to perform when a control signal is sent to this input.</param>
        public ControlleeInput( Action<T> signalResponse )
        {
            this.onInvoke = signalResponse;
        }

        public override void Disconnect()
        {
            ControllerOutput<T>.Disconnect( this, this.Output );
        }
    }
}